//! Apalis job that orchestrates wrapped-equity recovery.
//!
//! Enqueued per symbol with a positive `BaseWalletWrappedEquity` balance.
//! The job is a thin orchestrator: it reads `InventoryView`, picks a
//! dispatch path, and sends the command sequence through the aggregate's
//! store. All side effects (raindex deposit/confirm, mint/redemption
//! resume, wrapped-token lookup) live in the aggregate's command handlers
//! via its `Services`.
//!
//! Steps:
//!
//! 1. Claim the `equity_in_progress` guard for the symbol (from absent or
//!    `HeldForRecovery`). If a live transfer owns it (`ActiveTransfer`), the
//!    job reschedules itself with a delay so an unchanged wallet balance is
//!    not stranded waiting for another snapshot.
//! 2. Read the inventory view's wallet balance + active mint/redemption
//!    maps to pick a `DispatchDecision`.
//! 3. Send `Detect` followed by the path-specific command sequence:
//!    `DispatchToMint`, `DispatchToRedemption`, or `SubmitOrphanDeposit +
//!    ConfirmOrphanDeposit`. The aggregate's terminal state encodes the
//!    outcome; no separate completion command is needed.
//!
//! The job carries its `WrappedEquityRecoveryId` in the apalis payload
//! (generated by the reactor when pushing the job) so retries target the
//! same aggregate -- the next command in the sequence picks up wherever
//! the previous attempt stopped.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, RwLock};
use std::time::Duration;
use thiserror::Error;
use tracing::{debug, info, warn};

use st0x_event_sorcery::{SendError, Store};
use st0x_execution::{FractionalShares, Symbol};
use st0x_tokenization::IssuerRequestId;

use super::aggregate::{
    WrappedEquityRecovery, WrappedEquityRecoveryCommand, WrappedEquityRecoveryError,
    WrappedEquityRecoveryId,
};
use crate::conductor::job::{BackpressureStreak, Job, JobQueue, Label, QueuePushError};
use crate::equity_redemption::{EquityRedemption, RedemptionAggregateId};
use crate::inventory::BroadcastingInventory;
use crate::inventory::view::{InFlightEquityLocation, InventoryView};
use crate::rebalancing::trigger::{GuardState, claim_guard_for_recovery_or_orphan};
use crate::tokenized_equity_mint::TokenizedEquityMint;

/// Apalis queue type for [`WrappedEquityRecoveryJob`].
pub(crate) type WrappedEquityRecoveryJobQueue = JobQueue<WrappedEquityRecoveryJob>;

/// Dependencies the recovery job needs to claim the per-symbol concurrency
/// guard, read inventory, and send commands through the aggregate's store.
/// Services (raindex/wrapper/transfer) live on the store -- not here.
pub(crate) struct WrappedEquityRecoveryCtx {
    pub(crate) inventory: Arc<BroadcastingInventory>,
    pub(crate) store: Arc<Store<WrappedEquityRecovery>>,
    pub(crate) mint_store: Arc<Store<TokenizedEquityMint>>,
    pub(crate) redemption_store: Arc<Store<EquityRedemption>>,
    pub(crate) equity_in_progress: Arc<RwLock<HashMap<Symbol, GuardState>>>,
    /// Queue used for delayed self-reschedule when the shared equity guard is
    /// held by another recovery/transfer job.
    pub(crate) queue: WrappedEquityRecoveryJobQueue,
    pub(crate) reschedule_interval: Duration,
}

/// Why a single recovery job attempt failed. Errors propagate up through
/// apalis; service-call failures inside the aggregate's command handlers
/// are recorded as `RecoveryFailed` events and don't surface here.
#[derive(Debug, Error)]
pub(crate) enum WrappedEquityRecoveryJobError {
    #[error("recovery aggregate error: {0}")]
    Aggregate(#[from] SendError<WrappedEquityRecovery>),
    #[error(transparent)]
    Domain(#[from] WrappedEquityRecoveryError),
    #[error(
        "inventory view reports both an active mint ({mint_id}) and active redemption \
         ({redemption_id}) for symbol {symbol} -- aborting recovery"
    )]
    ConflictingActiveTransfers {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },
    #[error(
        "active mint {mint_id} for symbol {symbol} carries quantity {aggregate_shares}, \
         which does not match the wrapped-equity wallet snapshot {snapshot_shares} -- \
         refusing to dispatch to a stale aggregate"
    )]
    ActiveMintQuantityMismatch {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },
    #[error(
        "active redemption {redemption_id} for symbol {symbol} carries quantity \
         {aggregate_shares}, which does not match the wrapped-equity wallet snapshot \
         {snapshot_shares} -- refusing to dispatch to a stale aggregate"
    )]
    ActiveRedemptionQuantityMismatch {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },
    #[error("active mint {mint_id} for symbol {symbol} is missing from the mint store")]
    ActiveMintMissing {
        symbol: Symbol,
        mint_id: IssuerRequestId,
    },
    #[error(
        "active redemption {redemption_id} for symbol {symbol} is missing from the \
         redemption store"
    )]
    ActiveRedemptionMissing {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
    },
    #[error("active mint store error: {0}")]
    ActiveMintAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::tokenized_equity_mint::TokenizedEquityMint>,
        >,
    ),
    #[error("active redemption store error: {0}")]
    ActiveRedemptionAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::equity_redemption::EquityRedemption>,
        >,
    ),
    #[error("failed to reschedule recovery job after guard contention: {0}")]
    Reschedule(#[from] QueuePushError),
}

/// Apalis job payload. The reactor pushes one of these per symbol with a
/// positive `BaseWalletWrappedEquity` balance, generating a fresh
/// `recovery_id` at push time so apalis retries hit the same aggregate.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct WrappedEquityRecoveryJob {
    pub(crate) symbol: Symbol,
    pub(crate) recovery_id: WrappedEquityRecoveryId,
    /// Count of consecutive broker rate-limit (429) reschedules leading up to
    /// this attempt (RAI-1494). `#[serde(default)]` so a row enqueued under
    /// the pre-this-change payload shape still deserializes to `0` instead of
    /// crashing the poll stream's `sqlx::Decode`.
    ///
    /// NOT YET wired to a reschedule: `resume_mint`/`resume_redemption`
    /// failures are caught inside the aggregate's command handler and
    /// recorded as a terminal `RecoveryFailed` event with only a
    /// Display-formatted `String` reason (see `resume_mint_or_fail` /
    /// `resume_redemption_or_fail` in `aggregate.rs`) -- `ctx.store.send()`
    /// therefore returns `Ok(())` regardless, so `perform()` never observes
    /// an `Err` to classify for this failure class, and `find_backpressure`
    /// cannot walk to a real Alpaca error type from any constructible
    /// `WrappedEquityRecoveryJobError` today. This is pre-existing behavior,
    /// not a regression: a 429 here has always immediately terminalized the
    /// recovery with zero retries. Closing this gap needs the aggregate's
    /// error type to preserve the classified error (not just its Display
    /// string) and `transition()` to return `Err` instead of
    /// `Ok(RecoveryFailed)` on a classified 429, plus threading this streak
    /// into the `Command` (the aggregate has no visibility into the job's own
    /// payload) -- a redesign of the aggregate's error contract, out of scope
    /// for this task's per-job wiring. Field added now so the payload schema
    /// is ready when that follow-up lands.
    #[serde(default)]
    pub(crate) backpressure_streak: BackpressureStreak,
}

impl Job<WrappedEquityRecoveryCtx> for WrappedEquityRecoveryJob {
    type Output = ();
    type Error = WrappedEquityRecoveryJobError;

    const WORKER_NAME: &'static str = "wrapped-equity-recovery-worker";

    #[cfg(any(test, feature = "test-support"))]
    const JOB_KIND: crate::conductor::job::JobKind =
        crate::conductor::job::JobKind::WrappedEquityRecovery;

    fn label(&self) -> Label {
        Label::new(format!(
            "WrappedEquityRecovery:{}:{}",
            self.symbol, self.recovery_id
        ))
    }

    async fn perform(&self, ctx: &WrappedEquityRecoveryCtx) -> Result<Self::Output, Self::Error> {
        let symbol = self.symbol.clone();

        // Two-path claim: this job handles a positive `BaseWalletWrapped`
        // balance, which can be either an orphan (absent guard) or the
        // landed-but-unconfirmed `WrapSubmitted` outcome -- the wrap tx
        // actually landed so the tokens are WRAPPED, but the confirmation read
        // failed and the transfer job handed the slot to recovery as
        // `HeldForRecovery`. Claiming `HeldForRecovery` here is what drains that
        // slot; refusing it (as the old orphan-only claim did) left it wedged
        // because `UnwrappedEquityRecovery` `NoBalanceSkip`s on a wrapped
        // balance. The atomic claim makes a concurrent `UnwrappedEquityRecovery`
        // claim safe -- only one wins, the other reschedules. Returns None only
        // for `ActiveTransfer` (a live transfer job owns the slot).
        let Some(guard) = claim_guard_for_recovery_or_orphan(&ctx.equity_in_progress, &symbol)
        else {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Rescheduling wrapped equity recovery: equity_in_progress held by \
                 active transfer; deferring",
            );
            ctx.queue
                .clone()
                .push_with_delay(self.clone(), ctx.reschedule_interval)
                .await?;
            return Ok(());
        };

        if let Some(agg) = ctx.store.load(&self.recovery_id).await?
            && agg.is_terminal()
        {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Skipping wrapped equity recovery: aggregate already terminal",
            );
            guard.release();
            return Ok(());
        }

        let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, &symbol).await else {
            // No wrapped balance to drain this cycle. Do NOT release the guard:
            // an orphan claim drops to absent (the reactor re-triggers on the
            // next positive-balance poll), while a `HeldForRecovery` claim drops
            // back to `HeldForRecovery`. The reactor only re-dispatches on a
            // POSITIVE balance, so a `HeldForRecovery`-origin claim that finds
            // zero balance must self-reschedule or the slot wedges with no job
            // left to drain it.
            if guard.claimed_from_held_for_recovery() {
                debug!(
                    target: "rebalance",
                    %symbol,
                    recovery_id = %self.recovery_id,
                    "Rescheduling wrapped equity recovery: no positive balance yet but slot \
                     is HeldForRecovery; re-enqueueing with delay to keep polling until the \
                     balance resolves or the slot is cleared",
                );
                ctx.queue
                    .clone()
                    .push_with_delay(self.clone(), ctx.reschedule_interval)
                    .await?;
            } else {
                debug!(
                    target: "rebalance",
                    %symbol,
                    recovery_id = %self.recovery_id,
                    "Skipping wrapped equity recovery: no positive balance in inventory view; \
                     orphan claim, guard drop removes entry so future inventory polls can \
                     re-trigger recovery",
                );
            }
            return Ok(());
        };

        if let Err(error) = validate_active_aggregate_quantity(ctx, &symbol, &snapshot).await {
            warn!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                %error,
                "Wrapped equity recovery: active aggregate quantity mismatch; \
                 skipping dispatch",
            );
            // Validation failure is a retryable error: guard drops normally,
            // restoring its claim origin (orphan removes the entry;
            // HeldForRecovery restores HeldForRecovery for the next retry).
            return Err(error);
        }

        ctx.store
            .send(
                &self.recovery_id,
                WrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: snapshot.shares,
                },
            )
            .await?;

        info!(
            target: "rebalance",
            %symbol,
            recovery_id = %self.recovery_id,
            shares = %snapshot.shares,
            ?snapshot.dispatch,
            "Wrapped equity recovery: dispatched detection",
        );

        let result = match snapshot.dispatch {
            DispatchDecision::ActiveMint(mint_id) => ctx
                .store
                .send(
                    &self.recovery_id,
                    WrappedEquityRecoveryCommand::DispatchToMint { mint_id },
                )
                .await
                .map_err(Into::into),
            DispatchDecision::ActiveRedemption(redemption_id) => ctx
                .store
                .send(
                    &self.recovery_id,
                    WrappedEquityRecoveryCommand::DispatchToRedemption { redemption_id },
                )
                .await
                .map_err(Into::into),
            DispatchDecision::Orphan => {
                ctx.store
                    .send(
                        &self.recovery_id,
                        WrappedEquityRecoveryCommand::SubmitOrphanDeposit,
                    )
                    .await?;
                if let Some(agg) = ctx.store.load(&self.recovery_id).await?
                    && agg.is_terminal()
                {
                    Ok(())
                } else {
                    ctx.store
                        .send(
                            &self.recovery_id,
                            WrappedEquityRecoveryCommand::ConfirmOrphanDeposit,
                        )
                        .await
                        .map_err(Into::into)
                }
            }
            DispatchDecision::Conflict {
                mint_id,
                redemption_id,
            } => {
                let reason = format!(
                    "InventoryView reports active mint {mint_id} and active redemption \
                     {redemption_id} for symbol {symbol}; refusing to dispatch"
                );
                warn!(target: "rebalance", %symbol, %mint_id, %redemption_id, "Wrapped equity recovery: conflict");
                ctx.store
                    .send(
                        &self.recovery_id,
                        WrappedEquityRecoveryCommand::FailRecovery { reason },
                    )
                    .await?;
                // Aggregate is now terminal (FailRecovery). Release the guard
                // directly here so future transfers are not permanently blocked.
                guard.release();
                return Err(WrappedEquityRecoveryJobError::ConflictingActiveTransfers {
                    symbol: symbol.clone(),
                    mint_id,
                    redemption_id,
                });
            }
        };

        // Release the guard on success (removes the slot). On non-terminal
        // failure, the guard drops normally: an orphan-origin claim removes the
        // entry, while a HeldForRecovery-origin claim restores HeldForRecovery
        // for a later recovery attempt.
        if result.is_ok() {
            guard.release();
        }
        result
    }
}

struct RecoverySnapshot {
    shares: st0x_execution::FractionalShares,
    dispatch: DispatchDecision,
}

#[derive(Debug)]
enum DispatchDecision {
    ActiveMint(IssuerRequestId),
    ActiveRedemption(RedemptionAggregateId),
    Orphan,
    /// `InventoryView` reports both an active mint and an active redemption
    /// for the same symbol. A symbol can only be in one in-flight transfer
    /// at a time -- this is a corrupt-state signal, not a normal dispatch
    /// path.
    Conflict {
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },
}

async fn read_recovery_snapshot(
    inventory: &BroadcastingInventory,
    symbol: &Symbol,
) -> Option<RecoverySnapshot> {
    let view = inventory.read().await;
    let shares = view.inflight_equity_at(symbol, InFlightEquityLocation::BaseWalletWrapped)?;
    if shares == st0x_execution::FractionalShares::ZERO {
        return None;
    }
    let dispatch = decide_dispatch(&view, symbol);
    drop(view);
    Some(RecoverySnapshot { shares, dispatch })
}

/// Confirms the active mint or redemption aggregate carries the same quantity
/// as the wrapped wallet snapshot. Without this check, the recovery stream
/// would record `snapshot.shares` for an aggregate that was actually set up
/// for a different amount, leaving the audit trail and the resumed work
/// disagreeing on how many shares moved.
async fn validate_active_aggregate_quantity(
    ctx: &WrappedEquityRecoveryCtx,
    symbol: &Symbol,
    snapshot: &RecoverySnapshot,
) -> Result<(), WrappedEquityRecoveryJobError> {
    match &snapshot.dispatch {
        DispatchDecision::ActiveMint(mint_id) => {
            let mint = ctx.mint_store.load(mint_id).await?.ok_or_else(|| {
                WrappedEquityRecoveryJobError::ActiveMintMissing {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                }
            })?;
            let aggregate_shares = FractionalShares::new(mint.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(WrappedEquityRecoveryJobError::ActiveMintQuantityMismatch {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                    snapshot_shares: snapshot.shares,
                    aggregate_shares,
                });
            }
            Ok(())
        }
        DispatchDecision::ActiveRedemption(redemption_id) => {
            let redemption = ctx
                .redemption_store
                .load(redemption_id)
                .await?
                .ok_or_else(|| WrappedEquityRecoveryJobError::ActiveRedemptionMissing {
                    symbol: symbol.clone(),
                    redemption_id: redemption_id.clone(),
                })?;
            let aggregate_shares = FractionalShares::new(redemption.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(
                    WrappedEquityRecoveryJobError::ActiveRedemptionQuantityMismatch {
                        symbol: symbol.clone(),
                        redemption_id: redemption_id.clone(),
                        snapshot_shares: snapshot.shares,
                        aggregate_shares,
                    },
                );
            }
            Ok(())
        }
        DispatchDecision::Orphan | DispatchDecision::Conflict { .. } => Ok(()),
    }
}

fn decide_dispatch(view: &InventoryView, symbol: &Symbol) -> DispatchDecision {
    match (view.active_mint(symbol), view.active_redemption(symbol)) {
        (Some(mint_id), Some(redemption_id)) => DispatchDecision::Conflict {
            mint_id: mint_id.clone(),
            redemption_id: redemption_id.clone(),
        },
        (Some(mint_id), None) => DispatchDecision::ActiveMint(mint_id.clone()),
        (None, Some(redemption_id)) => DispatchDecision::ActiveRedemption(redemption_id.clone()),
        (None, None) => DispatchDecision::Orphan,
    }
}

#[cfg(test)]
mod tests {
    use alloy::primitives::Address;
    use std::sync::{Arc, RwLock};
    use tokio::sync::broadcast;
    use uuid::Uuid;

    use st0x_event_sorcery::test_store;
    use st0x_raindex::Raindex;
    use st0x_tokenization::mock::MockTokenizer;
    use st0x_wrapper::{MockWrapper, Wrapper};

    use super::super::aggregate::WrappedEquityRecoveryServices;
    use super::*;
    use crate::inventory::BroadcastingInventory;
    use crate::inventory::view::InventoryView;
    use crate::onchain::mock::MockRaindex;
    use crate::rebalancing::equity::{CrossVenueEquityTransfer, EquityTransferServices};
    use crate::vault_lookup::{MockVaultLookup, VaultLookup};

    #[test]
    fn wrapped_equity_recovery_job_payload_without_backpressure_streak_deserializes_to_zero() {
        let payload = serde_json::json!({
            "symbol": Symbol::new("AAPL").unwrap(),
            "recovery_id": WrappedEquityRecoveryId(Uuid::new_v4()),
        });

        let job: WrappedEquityRecoveryJob = serde_json::from_value(payload).unwrap();
        assert_eq!(job.backpressure_streak, BackpressureStreak::default());
    }

    #[tokio::test]
    async fn guard_contention_reschedules_without_dropping_the_recovery() {
        let symbol = Symbol::new("AAPL").unwrap();
        let equity_in_progress = Arc::new(RwLock::new(HashMap::from([(
            symbol.clone(),
            GuardState::ActiveTransfer { generation: 0 },
        )])));

        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let vault_lookup: Arc<dyn VaultLookup> = Arc::new(MockVaultLookup::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let transfer_services = EquityTransferServices {
            raindex: raindex.clone(),
            vault_lookup: vault_lookup.clone(),
            tokenizer: Arc::new(MockTokenizer::new()),
            wrapper: wrapper.clone(),
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            vault_lookup.clone(),
            Arc::new(MockTokenizer::new()),
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let store = Arc::new(test_store(
            pool.clone(),
            WrappedEquityRecoveryServices {
                raindex,
                vault_lookup,
                wrapper,
                transfer,
            },
        ));

        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(InventoryView::default(), sender));
        let ctx = WrappedEquityRecoveryCtx {
            inventory,
            store,
            mint_store,
            redemption_store,
            equity_in_progress,
            queue: WrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        };
        let job = WrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
            backpressure_streak: BackpressureStreak::default(),
        };

        job.perform(&ctx).await.unwrap();

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "guard-held perform() must not start recovery; aggregate should be absent, got {state:?}",
        );

        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<WrappedEquityRecoveryJob>())
                .fetch_one(ctx.queue.pool())
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 1,
            "guard contention must reschedule the wrapped recovery job, not mark it done",
        );
    }

    #[tokio::test]
    async fn enqueue_dedup_matches_symbol_exactly_not_as_substring() {
        let apalis_pool = crate::test_utils::setup_test_apalis_pool().await;

        let mut queue = WrappedEquityRecoveryJobQueue::new(&apalis_pool);
        queue
            .push(WrappedEquityRecoveryJob {
                symbol: Symbol::new("GOOGL").unwrap(),
                recovery_id: WrappedEquityRecoveryId(Uuid::new_v4()),
                backpressure_streak: BackpressureStreak::default(),
            })
            .await
            .unwrap();

        // The exact query the reactor uses to dedupe wrapped-recovery enqueues.
        const DEDUP_QUERY: &str = "SELECT COUNT(*) FROM Jobs \
             WHERE job_type = ? \
             AND status IN ('Pending', 'Queued', 'Running') \
             AND json_extract(job, '$.symbol') = ?";
        let job_type = std::any::type_name::<WrappedEquityRecoveryJob>();

        let (exact,): (i64,) = sqlx_apalis::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOGL")
            .fetch_one(&apalis_pool)
            .await
            .unwrap();
        assert_eq!(exact, 1, "exact symbol must match the queued GOOGL job");

        let (substring,): (i64,) = sqlx_apalis::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOG")
            .fetch_one(&apalis_pool)
            .await
            .unwrap();
        assert_eq!(
            substring, 0,
            "a substring ticker (GOOG) must not match the queued GOOGL job",
        );
    }
}
