//! Apalis job that orchestrates unwrapped-equity recovery.
//!
//! Enqueued per symbol with a positive `BaseWalletUnwrappedEquity`
//! balance. The job is a thin orchestrator: it reads `InventoryView`,
//! picks a dispatch path, and sends the command sequence through the
//! aggregate's store. All side effects (raindex deposit/confirm,
//! wrapper wrap/confirm, mint/redemption resume) live in the
//! aggregate's command handlers via its `Services`.
//!
//! Steps:
//!
//! 1. Claim the `equity_in_progress` guard for the symbol. If another
//!    task already holds it, the job reschedules itself with a delay
//!    (`push_with_delay`) and returns `Ok(())` rather than erroring --
//!    exhausting the apalis retry budget on a held guard fires the shared
//!    failure-notify and halts the whole monitor. The self-reschedule is
//!    required because a bare skip would strand the orphan: the inventory
//!    snapshot only re-emits `BaseWalletUnwrappedEquity` on a balance
//!    CHANGE, so an unchanged orphan balance has nothing to re-trigger the
//!    reactor. Rescheduling re-dispatches a fresh attempt once the guard
//!    frees, without consuming the retry budget.
//! 2. Read the inventory view's wallet balance + active mint/redemption
//!    maps to pick a `DispatchDecision`.
//! 3. Send `Detect` followed by the path-specific command sequence:
//!    `DispatchToMint`, `DispatchToRedemption`, or `SubmitOrphanWrap +
//!    ConfirmOrphanWrap + SubmitOrphanDeposit + ConfirmOrphanDeposit`.
//!    The aggregate's terminal state encodes the outcome; no separate
//!    completion command is needed.
//!
//! The job carries its `UnwrappedEquityRecoveryId` in the apalis
//! payload (generated by the reactor when pushing the job) so retries
//! target the same aggregate -- the next command in the sequence picks
//! up wherever the previous attempt stopped.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, RwLock};
use std::time::Duration;
use thiserror::Error;
use tracing::{debug, info, warn};

use st0x_event_sorcery::{AggregateError, LifecycleError, SendError, Store};
use st0x_execution::{FractionalShares, Symbol};
use st0x_tokenization::IssuerRequestId;

use super::aggregate::{
    UnwrappedEquityRecovery, UnwrappedEquityRecoveryCommand, UnwrappedEquityRecoveryError,
    UnwrappedEquityRecoveryId,
};
#[cfg(test)]
use crate::bot_gas::BotGasReceiptCostEnqueuer;
use crate::bot_gas::redrive::{BotGasFailureClassifier, redrive_on_bot_gas_failure};
use crate::conductor::job::{Job, JobQueue, Label, QueuePushError};
use crate::equity_redemption::{EquityRedemption, RedemptionAggregateId};
use crate::inventory::BroadcastingInventory;
use crate::inventory::view::{InFlightEquityLocation, InventoryView};
use crate::rebalancing::trigger::{GuardState, claim_guard_for_recovery_or_orphan};
use crate::tokenized_equity_mint::TokenizedEquityMint;

/// Apalis queue type for [`UnwrappedEquityRecoveryJob`].
pub(crate) type UnwrappedEquityRecoveryJobQueue = JobQueue<UnwrappedEquityRecoveryJob>;

/// Dependencies the recovery job needs to claim the per-symbol concurrency
/// guard, read inventory, and send commands through the aggregate's store.
/// Services (raindex/wrapper/transfer/wallet) live on the store -- not here.
pub(crate) struct UnwrappedEquityRecoveryCtx {
    pub(crate) inventory: Arc<BroadcastingInventory>,
    pub(crate) store: Arc<Store<UnwrappedEquityRecovery>>,
    pub(crate) mint_store: Arc<Store<TokenizedEquityMint>>,
    pub(crate) redemption_store: Arc<Store<EquityRedemption>>,
    pub(crate) equity_in_progress: Arc<RwLock<HashMap<Symbol, GuardState>>>,
    /// Queue the job re-pushes itself onto when it loses the per-symbol
    /// guard, so a skipped recovery is re-dispatched rather than stranded.
    pub(crate) queue: UnwrappedEquityRecoveryJobQueue,
    /// Delay before a guard-contention reschedule re-attempts. Sourced from
    /// the configured inventory poll interval.
    pub(crate) reschedule_interval: Duration,
}

/// Why a single recovery job attempt failed. Errors propagate up through
/// apalis; most service-call failures inside the aggregate's command
/// handlers are recorded as `RecoveryFailed` events and don't surface here.
/// The one exception is a bot-gas enqueue failure
/// (`UnwrappedEquityRecoveryError::BotGasEnqueueFailed`), which the
/// aggregate deliberately propagates so it reaches `perform`'s
/// `redrive_on_bot_gas_failure` call instead of permanently failing the
/// recovery over a best-effort accounting write.
#[derive(Debug, Error)]
pub(crate) enum UnwrappedEquityRecoveryJobError {
    #[error("recovery aggregate error: {0}")]
    Aggregate(#[from] SendError<UnwrappedEquityRecovery>),
    #[error(transparent)]
    Domain(#[from] UnwrappedEquityRecoveryError),
    #[error(
        "active mint {mint_id} for symbol {symbol} carries quantity {aggregate_shares}, \
         which does not match the unwrapped-equity wallet snapshot {snapshot_shares} -- \
         refusing to dispatch to a stale aggregate"
    )]
    ActiveMintQuantityMismatch {
        symbol: Symbol,
        mint_id: IssuerRequestId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },
    #[error(
        "active redemption {redemption_id} for symbol {symbol} carries quantity \
         {aggregate_shares}, which does not match the unwrapped-equity wallet snapshot \
         {snapshot_shares} -- refusing to dispatch to a stale aggregate"
    )]
    ActiveRedemptionQuantityMismatch {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
        snapshot_shares: FractionalShares,
        aggregate_shares: FractionalShares,
    },
    #[error("active mint {mint_id} for symbol {symbol} is missing from the mint store")]
    ActiveMintMissing {
        symbol: Symbol,
        mint_id: IssuerRequestId,
    },
    #[error(
        "active redemption {redemption_id} for symbol {symbol} is missing from the \
         redemption store"
    )]
    ActiveRedemptionMissing {
        symbol: Symbol,
        redemption_id: RedemptionAggregateId,
    },
    #[error("active mint store error: {0}")]
    ActiveMintAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::tokenized_equity_mint::TokenizedEquityMint>,
        >,
    ),
    #[error("active redemption store error: {0}")]
    ActiveRedemptionAggregate(
        #[from]
        st0x_event_sorcery::AggregateError<
            st0x_event_sorcery::LifecycleError<crate::equity_redemption::EquityRedemption>,
        >,
    ),
    #[error("failed to reschedule recovery job after guard contention: {0}")]
    Reschedule(#[from] QueuePushError),
    #[error(
        "no positive unwrapped balance in inventory view for symbol {symbol}; \
         guard drop restores HeldForRecovery or removes orphan entry"
    )]
    NoBalanceSkip { symbol: Symbol },
}

/// Apalis job payload. The reactor pushes one of these per symbol with a
/// positive `BaseWalletUnwrappedEquity` balance, generating a fresh
/// `recovery_id` at push time so apalis retries hit the same aggregate.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub(crate) struct UnwrappedEquityRecoveryJob {
    pub(crate) symbol: Symbol,
    pub(crate) recovery_id: UnwrappedEquityRecoveryId,
}

impl Job<UnwrappedEquityRecoveryCtx> for UnwrappedEquityRecoveryJob {
    type Output = ();
    type Error = UnwrappedEquityRecoveryJobError;

    const WORKER_NAME: &'static str = "unwrapped-equity-recovery-worker";

    #[cfg(any(test, feature = "test-support"))]
    const JOB_KIND: crate::conductor::job::JobKind =
        crate::conductor::job::JobKind::UnwrappedEquityRecovery;

    fn label(&self) -> Label {
        Label::new(format!(
            "UnwrappedEquityRecovery:{}:{}",
            self.symbol, self.recovery_id
        ))
    }

    async fn perform(&self, ctx: &UnwrappedEquityRecoveryCtx) -> Result<Self::Output, Self::Error> {
        let symbol = self.symbol.clone();

        // Two-path guard claim:
        // 1. `HeldForRecovery` -> `ActiveTransfer`: claim from a handoff set by
        //    the transfer job after a PostReceipt error. When the mint aggregate
        //    is in TokensReceived or WrapSubmitted, the ERC-4626 wrap reverted,
        //    tokens are UNWRAPPED in the base wallet, and this job is the correct
        //    deadlock-break claimant. (WrappedEquityRecovery handles the deposit-
        //    failed path when the aggregate is in TokensWrapped.)
        // 2. Absent -> `ActiveTransfer`: orphan path -- no active transfer was
        //    in progress; inventory detected a wallet balance independently.
        // 3. `ActiveTransfer`: a live transfer job owns the slot; reschedule.
        let Some(guard) = claim_guard_for_recovery_or_orphan(&ctx.equity_in_progress, &symbol)
        else {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Rescheduling unwrapped equity recovery: equity_in_progress held by active transfer",
            );
            ctx.queue
                .clone()
                .push_with_delay(self.clone(), ctx.reschedule_interval)
                .await?;
            return Ok(());
        };

        let current_state = ctx.store.load(&self.recovery_id).await?;

        if let Some(state) = &current_state
            && state.is_terminal()
        {
            debug!(
                target: "rebalance",
                %symbol,
                recovery_id = %self.recovery_id,
                "Skipping unwrapped equity recovery: aggregate already terminal",
            );
            guard.release();
            return Ok(());
        }

        let result = match current_state {
            None => start_from_detect(ctx, &self.recovery_id, &symbol).await,
            Some(UnwrappedEquityRecovery::Detected { shares, .. }) => {
                resume_from_detected(ctx, &self.recovery_id, &symbol, shares).await
            }
            Some(UnwrappedEquityRecovery::OrphanWrapSubmitted { .. }) => {
                resume_from_confirm_wrap(ctx, &self.recovery_id).await
            }
            Some(UnwrappedEquityRecovery::OrphanWrapped { .. }) => {
                resume_from_submit_deposit(ctx, &self.recovery_id).await
            }
            Some(UnwrappedEquityRecovery::OrphanDepositSubmitted { .. }) => {
                resume_from_confirm_deposit(ctx, &self.recovery_id).await
            }
            // Terminal states are already short-circuited by the `is_terminal`
            // early-return above; they are enumerated explicitly here (rather
            // than a `_` arm) so that adding a new non-terminal state fails to
            // compile until it is wired into a resume path, instead of silently
            // falling through to a no-op that never drives the recovery forward.
            Some(
                UnwrappedEquityRecovery::DispatchedToMint { .. }
                | UnwrappedEquityRecovery::DispatchedToRedemption { .. }
                | UnwrappedEquityRecovery::OrphanDeposited { .. }
                | UnwrappedEquityRecovery::Failed { .. },
            ) => Ok(()),
        };

        // Single exhaustive match on result:
        // - Ok(()): release guard (removes slot); recovery completed.
        // - Err(NoBalanceSkip): map to Ok(()) so apalis does NOT retry; guard
        //   drops normally (HeldForRecovery origin restores to HeldForRecovery;
        //   orphan removes). A HeldForRecovery-origin skip self-reschedules
        //   (push_with_delay) since the reactor only re-dispatches on a positive
        //   balance; an orphan skip relies on that next positive-balance poll.
        // - Err(other): propagate; guard drops, restoring prior state.
        match result {
            Ok(()) => {
                guard.release();
                Ok(())
            }
            Err(UnwrappedEquityRecoveryJobError::NoBalanceSkip { symbol: ref sym }) => {
                // No unwrapped balance to drain this cycle. The reactor only
                // re-dispatches recovery on a POSITIVE balance, so a
                // HeldForRecovery-origin claim that simply drops here would
                // restore HeldForRecovery with no job left to drain it --
                // wedging the symbol if the tokens left the wallet out of band.
                // Re-enqueue with a delay to keep polling. An orphan claim
                // instead drops to absent, so the next positive-balance poll
                // re-triggers it without help.
                if guard.claimed_from_held_for_recovery() {
                    debug!(
                        target: "rebalance",
                        symbol = %sym,
                        recovery_id = %self.recovery_id,
                        "Rescheduling unwrapped equity recovery: no balance yet but slot is \
                         HeldForRecovery; re-enqueueing with delay to keep polling until the \
                         balance resolves or the slot is cleared",
                    );
                    ctx.queue
                        .clone()
                        .push_with_delay(self.clone(), ctx.reschedule_interval)
                        .await?;
                } else {
                    info!(
                        target: "rebalance",
                        symbol = %sym,
                        "Unwrapped equity recovery: no balance in inventory view; orphan \
                         claim, guard drop removes the entry; next positive-balance poll \
                         re-dispatches",
                    );
                }
                Ok(())
            }
            // Bot-gas cost recording is best-effort (see
            // `BotGasReceiptCostEnqueuer`'s doc, ADR 0017 SS4): the shared
            // `redrive_on_bot_gas_failure` mechanism redrives rather than
            // consuming the apalis retry budget. The confirm step it follows
            // already succeeded and the aggregate has not advanced past it,
            // so redriving the same command is safe. The guard is left to
            // drop normally (not released) so the slot is restored/removed
            // exactly as any other retryable failure would.
            Err(other) => {
                redrive_on_bot_gas_failure(self, &ctx.queue, ctx.reschedule_interval, other).await
            }
        }
    }
}

/// Fresh recovery: read inventory, validate active-aggregate quantity, send
/// `Detect`, then dispatch from `Detected`.
async fn start_from_detect(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
    symbol: &Symbol,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, symbol).await else {
        debug!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            "Skipping unwrapped equity recovery: no positive balance in inventory view; \
             guard drop restores HeldForRecovery or removes orphan entry",
        );
        // Return Err so the caller does NOT call guard.release(). Drop restores
        // HeldForRecovery (if claimed from handoff) or removes the entry (orphan),
        // letting the next inventory poll re-trigger recovery once tokens are visible.
        return Err(UnwrappedEquityRecoveryJobError::NoBalanceSkip {
            symbol: symbol.clone(),
        });
    };

    validate_active_aggregate_quantity(ctx, symbol, &snapshot).await?;

    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::Detect {
                symbol: symbol.clone(),
                shares: snapshot.shares,
            },
        )
        .await?;

    info!(
        target: "rebalance",
        %symbol,
        %recovery_id,
        shares = %snapshot.shares,
        ?snapshot.dispatch,
        "Unwrapped equity recovery: dispatched detection",
    );

    dispatch_from_detected(ctx, recovery_id, symbol, snapshot.dispatch).await
}

/// Resume from `Detected`: a previous attempt persisted `Detect` but crashed
/// before any dispatch command landed. Re-read inventory and dispatch.
async fn resume_from_detected(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
    symbol: &Symbol,
    detected_shares: FractionalShares,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    let Some(snapshot) = read_recovery_snapshot(&ctx.inventory, symbol).await else {
        // Detected was persisted but the inventory no longer reports a positive
        // balance. The recovered tokens are either gone (recovered out-of-band)
        // or the previous snapshot was stale. Fail the aggregate so it leaves
        // the in-progress slot and a subsequent poll can start fresh.
        warn!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            "Resuming unwrapped recovery from Detected but inventory now reports zero balance; \
             failing the aggregate to free the symbol",
        );
        ctx.store
            .send(
                recovery_id,
                UnwrappedEquityRecoveryCommand::FailRecovery {
                    reason: "inventory reports zero unwrapped balance on resume from Detected"
                        .to_string(),
                },
            )
            .await?;
        return Ok(());
    };

    if snapshot.shares != detected_shares {
        warn!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            snapshot_shares = %snapshot.shares,
            %detected_shares,
            "Resuming unwrapped recovery from Detected but inventory shares changed; \
             failing the stale aggregate to allow a fresh recovery",
        );
        ctx.store
            .send(
                recovery_id,
                UnwrappedEquityRecoveryCommand::FailRecovery {
                    reason: format!(
                        "inventory shares changed on resume from Detected: detected \
                         {detected_shares}, current {}",
                        snapshot.shares
                    ),
                },
            )
            .await?;
        return Ok(());
    }

    // Mirror `start_from_detect`: a crash can land here after the inventory has
    // shifted, so re-validate the active mint/redemption quantity against the
    // fresh snapshot before dispatching rather than trusting the persisted
    // `Detected` state. Without this, the resume path would dispatch on a stale
    // aggregate that the fresh path would have rejected.
    if let Err(error) = validate_active_aggregate_quantity(ctx, symbol, &snapshot).await {
        if !is_business_validation_error(&error) {
            return Err(error);
        }

        // The persisted `Detected` aggregate's premise is stale: the active
        // mint/redemption no longer matches the wallet snapshot. Terminalize it
        // (mirroring the conflict branch) and return Ok, matching
        // `start_from_detect` for the identical failure: the aggregate is
        // already terminal, so an Err here would only burn an apalis retry
        // slot on a job with nothing left to do. A fresh poll then re-detects
        // from current inventory.
        warn!(
            target: "rebalance",
            %symbol,
            %recovery_id,
            %error,
            "Unwrapped equity recovery: active aggregate quantity mismatch on resume; failing recovery",
        );
        ctx.store
            .send(
                recovery_id,
                UnwrappedEquityRecoveryCommand::FailRecovery {
                    reason: format!("active aggregate validation failed on resume: {error}"),
                },
            )
            .await?;
        return Ok(());
    }

    info!(
        target: "rebalance",
        %symbol,
        %recovery_id,
        ?snapshot.dispatch,
        "Resuming unwrapped recovery from Detected",
    );

    dispatch_from_detected(ctx, recovery_id, symbol, snapshot.dispatch).await
}

/// Picks the dispatch command from a `Detected` state. For the orphan path,
/// chains into the four-step sequence; for active mint/redemption, sends the
/// single dispatch command; for conflict, fails the aggregate and returns
/// success so apalis does not retry a terminal domain rejection.
async fn dispatch_from_detected(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
    symbol: &Symbol,
    dispatch: DispatchDecision,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    match dispatch {
        DispatchDecision::ActiveMint(mint_id) => ctx
            .store
            .send(
                recovery_id,
                UnwrappedEquityRecoveryCommand::DispatchToMint { mint_id },
            )
            .await
            .map_err(Into::into),
        DispatchDecision::ActiveRedemption(redemption_id) => ctx
            .store
            .send(
                recovery_id,
                UnwrappedEquityRecoveryCommand::DispatchToRedemption { redemption_id },
            )
            .await
            .map_err(Into::into),
        DispatchDecision::Orphan => resume_from_submit_wrap(ctx, recovery_id).await,
        DispatchDecision::Conflict {
            mint_id,
            redemption_id,
        } => {
            let reason = format!(
                "InventoryView reports active mint {mint_id} and active redemption \
                 {redemption_id} for symbol {symbol}; refusing to dispatch"
            );
            warn!(target: "rebalance", %symbol, %mint_id, %redemption_id, "Unwrapped equity recovery: conflict");
            ctx.store
                .send(
                    recovery_id,
                    UnwrappedEquityRecoveryCommand::FailRecovery { reason },
                )
                .await?;
            Ok(())
        }
    }
}

fn is_business_validation_error(error: &UnwrappedEquityRecoveryJobError) -> bool {
    match error {
        UnwrappedEquityRecoveryJobError::ActiveMintQuantityMismatch { .. }
        | UnwrappedEquityRecoveryJobError::ActiveRedemptionQuantityMismatch { .. }
        | UnwrappedEquityRecoveryJobError::ActiveMintMissing { .. }
        | UnwrappedEquityRecoveryJobError::ActiveRedemptionMissing { .. } => true,
        UnwrappedEquityRecoveryJobError::Aggregate(_)
        | UnwrappedEquityRecoveryJobError::Domain(_)
        | UnwrappedEquityRecoveryJobError::ActiveMintAggregate(_)
        | UnwrappedEquityRecoveryJobError::ActiveRedemptionAggregate(_)
        | UnwrappedEquityRecoveryJobError::Reschedule(_)
        | UnwrappedEquityRecoveryJobError::NoBalanceSkip { .. } => false,
    }
}

impl BotGasFailureClassifier for UnwrappedEquityRecoveryJobError {
    fn is_bot_gas_enqueue_failure(&self) -> bool {
        match self {
            Self::Aggregate(AggregateError::UserError(LifecycleError::Apply(
                UnwrappedEquityRecoveryError::BotGasEnqueueFailed(_),
            ))) => true,
            Self::Aggregate(_)
            | Self::Domain(_)
            | Self::ActiveMintQuantityMismatch { .. }
            | Self::ActiveRedemptionQuantityMismatch { .. }
            | Self::ActiveMintMissing { .. }
            | Self::ActiveRedemptionMissing { .. }
            | Self::ActiveMintAggregate(_)
            | Self::ActiveRedemptionAggregate(_)
            | Self::Reschedule(_)
            | Self::NoBalanceSkip { .. } => false,
        }
    }
}

/// Starts the four-step orphan path. Each step is sent independently and
/// chains to the next via a `resume_from_*` function, so a retry that enters
/// at any orphan state can pick up at the right command instead of replaying
/// from `SubmitOrphanWrap`.
async fn resume_from_submit_wrap(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::SubmitOrphanWrap,
        )
        .await?;
    if aggregate_terminal(ctx, recovery_id).await? {
        return Ok(());
    }
    resume_from_confirm_wrap(ctx, recovery_id).await
}

/// Continues the orphan path from `OrphanWrapSubmitted` -- the wrap tx hash
/// is already persisted in state and the aggregate's command handler will
/// call `wrapper.confirm_wrap` on that tx.
async fn resume_from_confirm_wrap(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::ConfirmOrphanWrap,
        )
        .await?;
    if aggregate_terminal(ctx, recovery_id).await? {
        return Ok(());
    }
    resume_from_submit_deposit(ctx, recovery_id).await
}

/// Continues the orphan path from `OrphanWrapped` -- the wrapped amount is
/// persisted in state and the deposit command will use it.
async fn resume_from_submit_deposit(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::SubmitOrphanDeposit,
        )
        .await?;
    if aggregate_terminal(ctx, recovery_id).await? {
        return Ok(());
    }
    resume_from_confirm_deposit(ctx, recovery_id).await
}

/// Continues the orphan path from `OrphanDepositSubmitted` -- the deposit
/// tx hash is persisted in state and the aggregate confirms it via
/// `raindex.confirm_tx`.
async fn resume_from_confirm_deposit(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    ctx.store
        .send(
            recovery_id,
            UnwrappedEquityRecoveryCommand::ConfirmOrphanDeposit,
        )
        .await
        .map_err(Into::into)
}

async fn aggregate_terminal(
    ctx: &UnwrappedEquityRecoveryCtx,
    recovery_id: &UnwrappedEquityRecoveryId,
) -> Result<bool, UnwrappedEquityRecoveryJobError> {
    Ok(ctx
        .store
        .load(recovery_id)
        .await?
        .is_some_and(|agg| agg.is_terminal()))
}

struct RecoverySnapshot {
    shares: FractionalShares,
    dispatch: DispatchDecision,
}

#[derive(Debug)]
enum DispatchDecision {
    ActiveMint(IssuerRequestId),
    ActiveRedemption(RedemptionAggregateId),
    Orphan,
    /// `InventoryView` reports both an active mint and an active redemption
    /// for the same symbol. A symbol can only be in one in-flight transfer
    /// at a time -- this is a corrupt-state signal, not a normal dispatch
    /// path.
    Conflict {
        mint_id: IssuerRequestId,
        redemption_id: RedemptionAggregateId,
    },
}

async fn read_recovery_snapshot(
    inventory: &BroadcastingInventory,
    symbol: &Symbol,
) -> Option<RecoverySnapshot> {
    let view = inventory.read().await;
    let shares = view.inflight_equity_at(symbol, InFlightEquityLocation::BaseWalletUnwrapped)?;
    if shares == FractionalShares::ZERO {
        return None;
    }
    let dispatch = decide_dispatch(&view, symbol);
    drop(view);
    Some(RecoverySnapshot { shares, dispatch })
}

/// Confirms the active mint or redemption aggregate carries the same quantity
/// as the unwrapped wallet snapshot. Without this check, the recovery stream
/// would record `snapshot.shares` for an aggregate that was actually set up
/// for a different amount, leaving the audit trail and the resumed work
/// disagreeing on how many shares moved.
async fn validate_active_aggregate_quantity(
    ctx: &UnwrappedEquityRecoveryCtx,
    symbol: &Symbol,
    snapshot: &RecoverySnapshot,
) -> Result<(), UnwrappedEquityRecoveryJobError> {
    match &snapshot.dispatch {
        DispatchDecision::ActiveMint(mint_id) => {
            let mint = ctx.mint_store.load(mint_id).await?.ok_or_else(|| {
                UnwrappedEquityRecoveryJobError::ActiveMintMissing {
                    symbol: symbol.clone(),
                    mint_id: mint_id.clone(),
                }
            })?;
            let aggregate_shares = FractionalShares::new(mint.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(
                    UnwrappedEquityRecoveryJobError::ActiveMintQuantityMismatch {
                        symbol: symbol.clone(),
                        mint_id: mint_id.clone(),
                        snapshot_shares: snapshot.shares,
                        aggregate_shares,
                    },
                );
            }
            Ok(())
        }
        DispatchDecision::ActiveRedemption(redemption_id) => {
            let redemption = ctx
                .redemption_store
                .load(redemption_id)
                .await?
                .ok_or_else(
                    || UnwrappedEquityRecoveryJobError::ActiveRedemptionMissing {
                        symbol: symbol.clone(),
                        redemption_id: redemption_id.clone(),
                    },
                )?;
            let aggregate_shares = FractionalShares::new(redemption.quantity());
            if aggregate_shares != snapshot.shares {
                return Err(
                    UnwrappedEquityRecoveryJobError::ActiveRedemptionQuantityMismatch {
                        symbol: symbol.clone(),
                        redemption_id: redemption_id.clone(),
                        snapshot_shares: snapshot.shares,
                        aggregate_shares,
                    },
                );
            }
            Ok(())
        }
        DispatchDecision::Orphan | DispatchDecision::Conflict { .. } => Ok(()),
    }
}

fn decide_dispatch(view: &InventoryView, symbol: &Symbol) -> DispatchDecision {
    match (view.active_mint(symbol), view.active_redemption(symbol)) {
        (Some(mint_id), Some(redemption_id)) => DispatchDecision::Conflict {
            mint_id: mint_id.clone(),
            redemption_id: redemption_id.clone(),
        },
        (Some(mint_id), None) => DispatchDecision::ActiveMint(mint_id.clone()),
        (None, Some(redemption_id)) => DispatchDecision::ActiveRedemption(redemption_id.clone()),
        (None, None) => DispatchDecision::Orphan,
    }
}

#[cfg(test)]
mod tests {
    use alloy::primitives::{Address, B256, TxHash, U256};
    use chrono::Utc;
    use st0x_float_macro::float;
    use std::collections::BTreeMap;
    use tokio::sync::broadcast;
    use uuid::Uuid;

    use st0x_event_sorcery::test_store;
    use st0x_raindex::{Raindex, RaindexVaultId};
    use st0x_tokenization::Tokenizer;
    use st0x_tokenization::issuer_request_id;
    use st0x_tokenization::mock::{MockCompletionOutcome, MockDetectionOutcome, MockTokenizer};
    use st0x_wrapper::{MockWrapper, Wrapper};

    use crate::equity_redemption::{
        EquityRedemption, EquityRedemptionCommand, redemption_aggregate_id,
    };
    use crate::onchain::mock::MockRaindex;
    use crate::rebalancing::equity::{CrossVenueEquityTransfer, EquityTransferServices};
    use crate::rebalancing::trigger::InProgressGuard;
    use crate::tokenized_equity_mint::{TokenizedEquityMint, TokenizedEquityMintCommand};
    use crate::vault_lookup::MockVaultLookup;

    use super::super::aggregate::UnwrappedEquityRecoveryServices;
    use super::*;

    fn mock_vault_lookup() -> MockVaultLookup {
        MockVaultLookup::new()
            .with_vault(Address::ZERO, RaindexVaultId(B256::ZERO))
            .with_default_vault(RaindexVaultId(B256::ZERO))
    }

    /// Builds a fully-wired recovery ctx around the given inventory view and
    /// in-progress map, with every service backed by a succeeding mock.
    async fn test_ctx(
        view: InventoryView,
        equity_in_progress: HashMap<Symbol, GuardState>,
    ) -> UnwrappedEquityRecoveryCtx {
        test_ctx_with_tokenizer(view, equity_in_progress, Arc::new(MockTokenizer::new())).await
    }

    /// `test_ctx` with a caller-supplied tokenizer, for tests whose resumed
    /// mint/redemption must drive detection/completion polling to a terminal
    /// outcome.
    async fn test_ctx_with_tokenizer(
        view: InventoryView,
        equity_in_progress: HashMap<Symbol, GuardState>,
        tokenizer: Arc<dyn Tokenizer>,
    ) -> UnwrappedEquityRecoveryCtx {
        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let transfer_services = EquityTransferServices {
            raindex: raindex.clone(),
            vault_lookup: Arc::new(mock_vault_lookup()),
            tokenizer: tokenizer.clone(),
            wrapper: wrapper.clone(),
            bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            Arc::new(mock_vault_lookup()),
            tokenizer,
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let store = Arc::new(test_store(
            pool,
            UnwrappedEquityRecoveryServices {
                raindex,
                vault_lookup: Arc::new(mock_vault_lookup()),
                wrapper,
                transfer,
                wallet: Address::random(),
                bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
            },
        ));
        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(view, sender));

        UnwrappedEquityRecoveryCtx {
            inventory,
            store,
            mint_store,
            redemption_store,
            equity_in_progress: Arc::new(RwLock::new(equity_in_progress)),
            queue: UnwrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        }
    }

    fn view_with_unwrapped_balance(symbol: &Symbol, shares: FractionalShares) -> InventoryView {
        let mut balances = BTreeMap::new();
        balances.insert(symbol.clone(), shares);
        let now = Utc::now();
        InventoryView::default().set_inflight_equity_at_location(
            InFlightEquityLocation::BaseWalletUnwrapped,
            &balances,
            now,
            now,
        )
    }

    /// On guard contention the job must RESCHEDULE itself (`push_with_delay`)
    /// and return `Ok(())` -- neither erroring nor silently skipping. Erroring
    /// would exhaust the apalis retry budget on a held guard and trip the shared
    /// failure-notify, halting the monitor. A silent skip would strand the
    /// orphan: the inventory snapshot only re-emits `BaseWalletUnwrappedEquity`
    /// on a balance CHANGE, so an unchanged orphan balance has nothing to
    /// re-trigger the reactor. The reschedule re-dispatches a fresh attempt
    /// once the guard frees.
    #[tokio::test]
    async fn guard_contention_reschedules_without_halting_the_bot() {
        let symbol = Symbol::new("AAPL").unwrap();
        let equity_in_progress = Arc::new(RwLock::new(HashMap::from([(
            symbol.clone(),
            GuardState::ActiveTransfer { generation: 0 },
        )])));

        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let transfer_services = EquityTransferServices {
            raindex: raindex.clone(),
            vault_lookup: Arc::new(MockVaultLookup::new()),
            tokenizer: Arc::new(MockTokenizer::new()),
            wrapper: wrapper.clone(),
            bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            Arc::new(MockVaultLookup::new()),
            Arc::new(MockTokenizer::new()),
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let store = Arc::new(test_store(
            pool.clone(),
            UnwrappedEquityRecoveryServices {
                raindex,
                vault_lookup: Arc::new(MockVaultLookup::new()),
                wrapper,
                transfer,
                wallet: Address::random(),
                bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
            },
        ));

        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(InventoryView::default(), sender));

        let ctx = UnwrappedEquityRecoveryCtx {
            inventory,
            store,
            mint_store,
            redemption_store,
            equity_in_progress,
            queue: UnwrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        };

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };

        // Guard contention must NOT yield a retryable error (exhausting the retry
        // budget on a held guard fires the shared apalis failure_notify and halts
        // the monitor); the job reschedules itself and returns Ok instead.
        job.perform(&ctx).await.unwrap();

        // Recovery must NOT have started while the guard was held.
        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "guard-held perform() must not start recovery; aggregate should be absent, got {state:?}",
        );

        // ...but it MUST have rescheduled itself, or the unchanged orphan balance
        // would be stranded (the snapshot only re-emits on a balance change).
        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<UnwrappedEquityRecoveryJob>())
                .fetch_one(ctx.queue.pool())
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 1,
            "guard contention must reschedule the recovery job (push_with_delay), not silently skip",
        );
    }

    #[tokio::test]
    async fn resume_from_detected_validates_active_aggregate_quantity() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mint_id = issuer_request_id("missing-mint");

        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let transfer_services = EquityTransferServices {
            raindex: raindex.clone(),
            vault_lookup: Arc::new(MockVaultLookup::new()),
            tokenizer: Arc::new(MockTokenizer::new()),
            wrapper: wrapper.clone(),
            bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            Arc::new(MockVaultLookup::new()),
            Arc::new(MockTokenizer::new()),
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        let store = Arc::new(test_store(
            pool.clone(),
            UnwrappedEquityRecoveryServices {
                raindex,
                vault_lookup: Arc::new(MockVaultLookup::new()),
                wrapper,
                transfer,
                wallet: Address::random(),
                bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
            },
        ));

        // Inventory reports an unwrapped balance (so a snapshot exists) and an
        // active mint for the symbol (so dispatch resolves to `ActiveMint`), but
        // no such mint aggregate is persisted. The fresh path validates the
        // active-aggregate quantity before dispatching; the resume path must do
        // the same, surfacing `ActiveMintMissing` instead of blindly dispatching
        // on a stale aggregate.
        let mut balances = BTreeMap::new();
        balances.insert(symbol.clone(), FractionalShares::new(float!(5)));
        let now = Utc::now();
        let view = InventoryView::default()
            .set_inflight_equity_at_location(
                InFlightEquityLocation::BaseWalletUnwrapped,
                &balances,
                now,
                now,
            )
            .set_active_mint(symbol.clone(), mint_id.clone());

        let (sender, _receiver) = broadcast::channel(16);
        let inventory = Arc::new(BroadcastingInventory::new(view, sender));

        let ctx = UnwrappedEquityRecoveryCtx {
            inventory,
            store,
            mint_store,
            redemption_store,
            equity_in_progress: Arc::new(RwLock::new(HashMap::new())),
            queue: UnwrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        };

        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        // Persist `Detected` so resume_from_detected runs against a real
        // aggregate -- in production perform() only dispatches here for a loaded
        // `Detected` state.
        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();

        // Validation failure terminalizes the aggregate and returns Ok --
        // mirroring start_from_detect -- so apalis does not burn a retry slot
        // on a job whose aggregate is already terminal.
        resume_from_detected(
            &ctx,
            &recovery_id,
            &symbol,
            FractionalShares::new(float!(5)),
        )
        .await
        .unwrap();

        let state = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::Failed { reason, .. }) = state else {
            panic!("resume validation failure must fail the recovery, got {state:?}");
        };
        assert!(
            reason.contains(&mint_id.to_string()),
            "failure reason should identify the missing mint aggregate, got {reason}",
        );
    }

    #[tokio::test]
    async fn enqueue_dedup_matches_symbol_exactly_not_as_substring() {
        let apalis_pool = crate::test_utils::setup_test_apalis_pool().await;

        let mut queue = UnwrappedEquityRecoveryJobQueue::new(&apalis_pool);
        queue
            .push(UnwrappedEquityRecoveryJob {
                symbol: Symbol::new("GOOGL").unwrap(),
                recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
            })
            .await
            .unwrap();

        // The exact query the reactor uses to dedupe unwrapped-recovery enqueues.
        const DEDUP_QUERY: &str = "SELECT COUNT(*) FROM Jobs \
             WHERE job_type = ? \
             AND status IN ('Pending', 'Queued', 'Running') \
             AND json_extract(job, '$.symbol') = ?";
        let job_type = std::any::type_name::<UnwrappedEquityRecoveryJob>();

        let (exact,): (i64,) = sqlx_apalis::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOGL")
            .fetch_one(&apalis_pool)
            .await
            .unwrap();
        assert_eq!(exact, 1, "exact symbol must match the queued GOOGL job");

        let (substring,): (i64,) = sqlx_apalis::query_as(DEDUP_QUERY)
            .bind(job_type)
            .bind("GOOG")
            .fetch_one(&apalis_pool)
            .await
            .unwrap();
        assert_eq!(
            substring, 0,
            "a substring ticker (GOOG) must not match the queued GOOGL job",
        );
    }

    #[test]
    fn decide_dispatch_resolves_all_four_paths() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mint_id = issuer_request_id("ISS001");
        let redemption_id = redemption_aggregate_id("RED001");

        assert!(
            matches!(
                decide_dispatch(&InventoryView::default(), &symbol),
                DispatchDecision::Orphan
            ),
            "no active transfers should resolve to the orphan path",
        );

        let mint_only = InventoryView::default().set_active_mint(symbol.clone(), mint_id.clone());
        assert!(
            matches!(
                decide_dispatch(&mint_only, &symbol),
                DispatchDecision::ActiveMint(id) if id == mint_id
            ),
            "an active mint alone should resolve to ActiveMint",
        );

        let redemption_only =
            InventoryView::default().set_active_redemption(symbol.clone(), redemption_id.clone());
        assert!(
            matches!(
                decide_dispatch(&redemption_only, &symbol),
                DispatchDecision::ActiveRedemption(id) if id == redemption_id
            ),
            "an active redemption alone should resolve to ActiveRedemption",
        );

        let conflict = InventoryView::default()
            .set_active_mint(symbol.clone(), mint_id.clone())
            .set_active_redemption(symbol.clone(), redemption_id.clone());
        assert!(
            matches!(
                decide_dispatch(&conflict, &symbol),
                DispatchDecision::Conflict { mint_id: mid, redemption_id: rid }
                    if mid == mint_id && rid == redemption_id
            ),
            "both active should resolve to Conflict carrying both ids",
        );
    }

    #[test]
    fn claim_guard_for_recovery_or_orphan_blocks_active_transfer_and_releases_on_drop() {
        let symbol = Symbol::new("AAPL").unwrap();
        let map = Arc::new(RwLock::new(HashMap::new()));

        // Absent -> succeeds (orphan path).
        let guard = claim_guard_for_recovery_or_orphan(&map, &symbol)
            .expect("absent entry: first claim should succeed");
        assert!(
            matches!(
                map.read().unwrap().get(&symbol),
                Some(GuardState::ActiveTransfer { .. })
            ),
            "claiming from absent must insert ActiveTransfer",
        );

        // ActiveTransfer -> blocks.
        let contended = claim_guard_for_recovery_or_orphan(&map, &symbol);
        assert!(
            contended.is_none(),
            "a second claim while ActiveTransfer must return None",
        );

        drop(guard);
        assert!(
            !map.read().unwrap().contains_key(&symbol),
            "dropping the guard must remove the symbol from the in-progress map",
        );

        // After drop, absent again -> succeeds.
        claim_guard_for_recovery_or_orphan(&map, &symbol)
            .expect("claim should succeed again once released");
    }

    #[test]
    fn claim_guard_for_recovery_or_orphan_succeeds_from_held_for_recovery() {
        let symbol = Symbol::new("AAPL").unwrap();
        let map = Arc::new(RwLock::new(HashMap::from([(
            symbol.clone(),
            GuardState::HeldForRecovery,
        )])));

        let guard = claim_guard_for_recovery_or_orphan(&map, &symbol)
            .expect("HeldForRecovery must allow claim");
        assert!(
            matches!(
                map.read().unwrap().get(&symbol),
                Some(GuardState::ActiveTransfer { .. })
            ),
            "HeldForRecovery claim must transition to ActiveTransfer",
        );

        // Drop restores to HeldForRecovery (not removes) so recovery retries
        // can proceed but a new transfer job cannot start while tokens are
        // still stranded.
        drop(guard);
        assert_eq!(
            map.read().unwrap().get(&symbol),
            Some(&GuardState::HeldForRecovery),
            "dropping guard claimed from HeldForRecovery must restore to HeldForRecovery, \
             not remove, so recovery retries are not blocked",
        );
    }

    /// When the guard drops back to `HeldForRecovery` after a recovery failure,
    /// a new transfer claim must be blocked (no double-mint while tokens are stranded).
    #[test]
    fn recovery_guard_drop_to_held_for_recovery_blocks_new_transfer_claim() {
        let symbol = Symbol::new("AAPL").unwrap();
        let map = Arc::new(RwLock::new(HashMap::from([(
            symbol.clone(),
            GuardState::HeldForRecovery,
        )])));

        let guard = claim_guard_for_recovery_or_orphan(&map, &symbol)
            .expect("HeldForRecovery must allow claim");
        drop(guard);

        // The slot is now HeldForRecovery; a new transfer claim must fail.
        assert_eq!(
            map.read().unwrap().get(&symbol),
            Some(&GuardState::HeldForRecovery),
        );

        // Verify the restored HeldForRecovery actually blocks a new transfer claim.
        assert!(
            InProgressGuard::try_claim_for_transfer(symbol, Arc::clone(&map)).is_none(),
            "HeldForRecovery restored by Drop must block new transfer claims (prevents double-mint)"
        );
    }

    #[tokio::test]
    async fn read_recovery_snapshot_skips_zero_and_absent_balance() {
        let symbol = Symbol::new("AAPL").unwrap();

        let absent = test_ctx(InventoryView::default(), HashMap::new()).await;
        assert!(
            read_recovery_snapshot(&absent.inventory, &symbol)
                .await
                .is_none(),
            "an absent balance should yield no snapshot",
        );

        let zero = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::ZERO),
            HashMap::new(),
        )
        .await;
        assert!(
            read_recovery_snapshot(&zero.inventory, &symbol)
                .await
                .is_none(),
            "a zero balance should yield no snapshot",
        );

        let positive = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5))),
            HashMap::new(),
        )
        .await;
        let snapshot = read_recovery_snapshot(&positive.inventory, &symbol)
            .await
            .expect("a positive balance should yield a snapshot");
        assert_eq!(snapshot.shares, FractionalShares::new(float!(5)));
        assert!(
            matches!(snapshot.dispatch, DispatchDecision::Orphan),
            "no active transfers should make the snapshot an orphan dispatch",
        );
    }

    #[tokio::test]
    async fn validate_active_mint_quantity_accepts_exact_match() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mint_id = issuer_request_id("ISS001");
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;

        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::RequestMint {
                    issuer_request_id: mint_id.clone(),
                    symbol: symbol.clone(),
                    quantity: float!(5),
                    wallet: Address::random(),
                },
            )
            .await
            .expect("RequestMint should persist a mint aggregate");

        let snapshot = RecoverySnapshot {
            shares: FractionalShares::new(float!(5)),
            dispatch: DispatchDecision::ActiveMint(mint_id.clone()),
        };
        validate_active_aggregate_quantity(&ctx, &symbol, &snapshot)
            .await
            .expect("matching snapshot and aggregate quantity should validate");
    }

    #[tokio::test]
    async fn validate_active_mint_quantity_rejects_mismatch() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mint_id = issuer_request_id("ISS001");
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;

        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::RequestMint {
                    issuer_request_id: mint_id.clone(),
                    symbol: symbol.clone(),
                    quantity: float!(3),
                    wallet: Address::random(),
                },
            )
            .await
            .expect("RequestMint should persist a mint aggregate");

        let snapshot = RecoverySnapshot {
            shares: FractionalShares::new(float!(5)),
            dispatch: DispatchDecision::ActiveMint(mint_id.clone()),
        };
        let error = validate_active_aggregate_quantity(&ctx, &symbol, &snapshot)
            .await
            .unwrap_err();
        assert!(
            matches!(
                error,
                UnwrappedEquityRecoveryJobError::ActiveMintQuantityMismatch { .. }
            ),
            "a quantity mismatch between snapshot and aggregate must be rejected, got {error:?}",
        );
    }

    #[tokio::test]
    async fn validate_active_redemption_reports_missing_aggregate() {
        let symbol = Symbol::new("AAPL").unwrap();
        let redemption_id = redemption_aggregate_id("RED-NONEXISTENT");
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;

        let snapshot = RecoverySnapshot {
            shares: FractionalShares::new(float!(5)),
            dispatch: DispatchDecision::ActiveRedemption(redemption_id.clone()),
        };
        let error = validate_active_aggregate_quantity(&ctx, &symbol, &snapshot)
            .await
            .unwrap_err();
        assert!(
            matches!(
                error,
                UnwrappedEquityRecoveryJobError::ActiveRedemptionMissing { .. }
            ),
            "a redemption the view reports active but the store lacks must be reported, got {error:?}",
        );
    }

    /// End-to-end orphan path: a positive unwrapped balance with no active
    /// mint/redemption drives `perform` through the full four-step orphan
    /// sequence to the terminal `OrphanDeposited` state.
    #[tokio::test]
    async fn perform_drives_orphan_path_to_orphan_deposited() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5))),
            HashMap::new(),
        )
        .await;
        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };

        job.perform(&ctx)
            .await
            .expect("orphan recovery should run to completion");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            matches!(state, Some(UnwrappedEquityRecovery::OrphanDeposited { .. })),
            "the orphan path should terminate in OrphanDeposited, got {state:?}",
        );
    }

    #[tokio::test]
    async fn perform_fresh_active_validation_failure_is_retryable_error() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mint_id = issuer_request_id("missing-mint");
        let view = view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5)))
            .set_active_mint(symbol.clone(), mint_id);
        let ctx = test_ctx(view, HashMap::new()).await;
        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };

        let error = job
            .perform(&ctx)
            .await
            .expect_err("fresh active validation failure should propagate for retry");
        assert!(
            matches!(
                error,
                UnwrappedEquityRecoveryJobError::ActiveMintMissing { .. }
            ),
            "fresh active validation should surface ActiveMintMissing, got {error:?}",
        );

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "fresh validation failure must not create a partial recovery aggregate, got {state:?}",
        );
    }

    #[tokio::test]
    async fn perform_skips_when_inventory_reports_no_balance() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;
        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };

        job.perform(&ctx)
            .await
            .expect("a no-balance perform is a no-op");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            state.is_none(),
            "no inventory balance must not start a recovery aggregate, got {state:?}",
        );

        // Orphan-origin (absent guard) no-balance skip must NOT self-reschedule:
        // the slot drops to absent and the reactor re-triggers on the next
        // positive-balance poll. Only a HeldForRecovery-origin skip reschedules.
        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<UnwrappedEquityRecoveryJob>())
                .fetch_one(ctx.queue.pool())
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 0,
            "an orphan no-balance skip must NOT reschedule; the reactor re-triggers on next poll",
        );
    }

    /// When `start_from_detect` returns `NoBalanceSkip` and the guard was claimed
    /// from `HeldForRecovery`, Drop restores the slot to `HeldForRecovery` AND the
    /// job must self-reschedule with a delay. The inventory reactor only
    /// re-dispatches on a positive balance, so without the reschedule a slot whose
    /// tokens left the wallet out of band would wedge with no job to drain it.
    #[tokio::test]
    async fn perform_no_balance_skip_restores_held_for_recovery_and_reschedules() {
        let symbol = Symbol::new("AAPL").unwrap();

        // Inventory reports zero balance for the symbol (no tokens in wallet).
        let ctx = test_ctx(
            InventoryView::default(),
            HashMap::from([(symbol.clone(), GuardState::HeldForRecovery)]),
        )
        .await;

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };

        // Must return Ok(()) -- no apalis retry.
        job.perform(&ctx)
            .await
            .expect("no-balance skip must return Ok");

        // Guard must be restored to HeldForRecovery (Drop behavior for
        // HeldForRecovery origin without release()).
        assert_eq!(
            ctx.equity_in_progress.read().unwrap().get(&symbol),
            Some(&GuardState::HeldForRecovery),
            "no-balance skip from HeldForRecovery claim must restore to HeldForRecovery"
        );

        // A delayed job must have been enqueued so polling continues until the
        // balance resolves or the slot is cleared.
        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<UnwrappedEquityRecoveryJob>())
                .fetch_one(ctx.queue.pool())
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 1,
            "a HeldForRecovery-origin no-balance skip must enqueue a delayed job to keep polling",
        );
    }

    #[tokio::test]
    async fn perform_skips_already_terminal_aggregate() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5))),
            HashMap::new(),
        )
        .await;
        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();
        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::FailRecovery {
                    reason: "pre-terminalized".to_string(),
                },
            )
            .await
            .unwrap();

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("a terminal aggregate perform is a no-op");

        let state = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::Failed { reason, .. }) = &state else {
            panic!("a terminal aggregate must be left untouched, got {state:?}");
        };
        assert_eq!(
            reason.as_str(),
            "pre-terminalized",
            "the pre-terminalized failure reason must be preserved",
        );
    }

    /// An `InventoryView` reporting both an active mint and an active redemption
    /// is corrupt state: `perform` must terminalize the aggregate as `Failed`
    /// and then return `Ok(())` so apalis does not retry a terminal rejection.
    #[tokio::test]
    async fn perform_conflict_fails_recovery_without_retrying() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mint_id = issuer_request_id("ISS001");
        let redemption_id = redemption_aggregate_id("RED001");
        let view = view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5)))
            .set_active_mint(symbol.clone(), mint_id.clone())
            .set_active_redemption(symbol.clone(), redemption_id.clone());
        let ctx = test_ctx(view, HashMap::new()).await;
        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };

        job.perform(&ctx)
            .await
            .expect("an inventory conflict should terminalize without retrying");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        assert!(
            matches!(state, Some(UnwrappedEquityRecovery::Failed { .. })),
            "a conflict must terminalize the aggregate as Failed, got {state:?}",
        );
    }

    /// Crash-recovery: `Detected` was persisted, then the worker crashed before
    /// dispatch. Retrying the same job should use the persisted recovery ID and
    /// current matching snapshot to continue the orphan path to completion.
    #[tokio::test]
    async fn perform_resume_from_detected_with_matching_snapshot_completes_orphan_path() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5))),
            HashMap::new(),
        )
        .await;
        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("Detected retry with matching snapshot should complete");

        let state = ctx.store.load(&recovery_id).await.unwrap();
        assert!(
            matches!(state, Some(UnwrappedEquityRecovery::OrphanDeposited { .. })),
            "Detected retry should complete the orphan path, got {state:?}",
        );
    }

    /// Crash-recovery: if the current inventory balance changed after
    /// `Detected` was persisted, the old recovery stream is stale and must
    /// terminalize instead of dispatching a command with mismatched audit data.
    #[tokio::test]
    async fn perform_resume_from_detected_with_changed_shares_fails_stale_aggregate() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(3))),
            HashMap::new(),
        )
        .await;
        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("stale Detected retry should terminalize without retrying");

        let state = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::Failed { reason, .. }) = state else {
            panic!("stale Detected retry must fail the aggregate, got {state:?}");
        };
        assert!(
            reason.contains("inventory shares changed"),
            "failure reason should explain changed shares, got {reason}",
        );
    }

    /// Crash-recovery: `Detected` was persisted, but by the time the retry
    /// runs the inventory no longer reports a balance (tokens recovered
    /// out-of-band). The resume must fail the aggregate -- freeing the symbol
    /// slot -- rather than leaving it stuck in `Detected` forever.
    #[tokio::test]
    async fn perform_resume_from_detected_with_zero_balance_fails_aggregate() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(InventoryView::default(), HashMap::new()).await;
        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("zero-balance resume must not burn an apalis retry slot");

        let state = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::Failed { reason, .. }) = state else {
            panic!("zero-balance resume must fail the aggregate, got {state:?}");
        };
        assert!(
            reason.contains("zero unwrapped balance"),
            "failure reason should explain the stale balance, got {reason}",
        );
    }

    /// Job-level routing: an active mint for the symbol must dispatch
    /// `DispatchToMint` -- not the orphan path, which would wrap tokens that
    /// are already part of an in-flight mint.
    #[tokio::test]
    async fn perform_drives_active_mint_path_to_dispatched_to_mint() {
        let symbol = Symbol::new("AAPL").unwrap();
        let mint_id = issuer_request_id("ISS001");
        let view = view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5)))
            .set_active_mint(symbol.clone(), mint_id.clone());
        let ctx = test_ctx(view, HashMap::new()).await;

        // Seed the mint to `TokensWrapped` so `resume_mint` runs to completion
        // under the succeeding mocks:
        // RequestMint -> (Poll) TokensReceived -> WrapSubmitted -> TokensWrapped.
        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::RequestMint {
                    issuer_request_id: mint_id.clone(),
                    symbol: symbol.clone(),
                    quantity: float!(5),
                    wallet: Address::random(),
                },
            )
            .await
            .unwrap();
        ctx.mint_store
            .send(&mint_id, TokenizedEquityMintCommand::Poll)
            .await
            .unwrap();
        let wrap_tx = TxHash::random();
        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::SubmitWrap {
                    wrap_tx_hash: wrap_tx,
                },
            )
            .await
            .unwrap();
        ctx.mint_store
            .send(
                &mint_id,
                TokenizedEquityMintCommand::WrapTokens {
                    wrap_tx_hash: wrap_tx,
                    wrapped_shares: U256::from(5_000_000_000_000_000_000u128),
                    wrap_block: 1,
                },
            )
            .await
            .unwrap();

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };
        job.perform(&ctx)
            .await
            .expect("active-mint recovery should run to completion");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::DispatchedToMint {
            mint_id: dispatched,
            ..
        }) = state
        else {
            panic!("active mint must route to DispatchedToMint, got {state:?}");
        };
        assert_eq!(
            dispatched, mint_id,
            "the dispatched mint id must be the active mint from the inventory",
        );

        let mint = ctx.mint_store.load(&mint_id).await.unwrap();
        assert!(
            matches!(mint, Some(TokenizedEquityMint::DepositedIntoRaindex { .. })),
            "resume_mint must drive the seeded mint to completion, got {mint:?}",
        );
    }

    /// Job-level routing: an active redemption for the symbol must dispatch
    /// `DispatchToRedemption`, resuming the in-flight redemption rather than
    /// orphan-wrapping its tokens.
    #[tokio::test]
    async fn perform_drives_active_redemption_path_to_dispatched_to_redemption() {
        let symbol = Symbol::new("AAPL").unwrap();
        let redemption_id = redemption_aggregate_id("RED001");
        let view = view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5)))
            .set_active_redemption(symbol.clone(), redemption_id.clone());
        let tokenizer = Arc::new(
            MockTokenizer::new()
                .with_detection_outcome(MockDetectionOutcome::Detected)
                .with_completion_outcome(MockCompletionOutcome::Completed),
        );
        let ctx = test_ctx_with_tokenizer(view, HashMap::new(), tokenizer).await;

        // Seed the redemption at `VaultWithdrawSubmitted` (Redeem submits the
        // withdrawal); `resume_redemption` walks it to `Completed` under the
        // detection/completion-configured mocks.
        ctx.redemption_store
            .send(
                &redemption_id,
                EquityRedemptionCommand::Redeem {
                    symbol: symbol.clone(),
                    quantity: float!(5),
                    token: Address::random(),
                    amount: FractionalShares::new(float!(5))
                        .to_u256_18_decimals()
                        .unwrap(),
                },
            )
            .await
            .unwrap();

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: UnwrappedEquityRecoveryId(Uuid::new_v4()),
        };
        job.perform(&ctx)
            .await
            .expect("active-redemption recovery should run to completion");

        let state = ctx.store.load(&job.recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::DispatchedToRedemption {
            redemption_id: dispatched,
            ..
        }) = state
        else {
            panic!("active redemption must route to DispatchedToRedemption, got {state:?}");
        };
        assert_eq!(
            dispatched, redemption_id,
            "the dispatched redemption id must be the active redemption from the inventory",
        );

        let redemption = ctx.redemption_store.load(&redemption_id).await.unwrap();
        assert!(
            matches!(redemption, Some(EquityRedemption::Completed { .. })),
            "resume_redemption must drive the seeded redemption to completion, got {redemption:?}",
        );
    }

    /// Crash between `SubmitOrphanWrap` and `ConfirmOrphanWrap`: the next
    /// `perform` must resume at the confirm step against the persisted tx
    /// hash, never submitting a second wrap.
    #[tokio::test]
    async fn perform_resumes_from_orphan_wrap_submitted_without_rewrapping() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5))),
            HashMap::new(),
        )
        .await;
        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();
        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::SubmitOrphanWrap,
            )
            .await
            .unwrap();

        let seeded = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::OrphanWrapSubmitted {
            wrap_tx_hash: seeded_wrap_tx,
            ..
        }) = seeded
        else {
            panic!("seeding should land in OrphanWrapSubmitted, got {seeded:?}");
        };

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("resume from OrphanWrapSubmitted should run to completion");

        let state = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::OrphanDeposited { wrap_tx_hash, .. }) = state else {
            panic!("resume must complete the orphan path, got {state:?}");
        };
        assert_eq!(
            wrap_tx_hash, seeded_wrap_tx,
            "the resumed run must confirm the persisted wrap tx, not submit a second wrap",
        );
    }

    /// Crash between `ConfirmOrphanWrap` and `SubmitOrphanDeposit`: the next
    /// `perform` must resume at the deposit step, preserving the original
    /// wrap tx hash.
    #[tokio::test]
    async fn perform_resumes_from_orphan_wrapped_without_rewrapping() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5))),
            HashMap::new(),
        )
        .await;
        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();
        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::SubmitOrphanWrap,
            )
            .await
            .unwrap();
        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::ConfirmOrphanWrap,
            )
            .await
            .unwrap();

        let seeded = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::OrphanWrapped {
            wrap_tx_hash: seeded_wrap_tx,
            ..
        }) = seeded
        else {
            panic!("seeding should land in OrphanWrapped, got {seeded:?}");
        };

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("resume from OrphanWrapped should run to completion");

        let state = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::OrphanDeposited { wrap_tx_hash, .. }) = state else {
            panic!("resume must complete the orphan path, got {state:?}");
        };
        assert_eq!(
            wrap_tx_hash, seeded_wrap_tx,
            "the resumed run must deposit the already-wrapped tokens, not re-wrap",
        );
    }

    /// Crash between `SubmitOrphanDeposit` and `ConfirmOrphanDeposit`: the
    /// next `perform` must confirm the persisted deposit tx rather than
    /// re-submitting the deposit.
    #[tokio::test]
    async fn perform_resumes_from_orphan_deposit_submitted_without_redepositing() {
        let symbol = Symbol::new("AAPL").unwrap();
        let ctx = test_ctx(
            view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5))),
            HashMap::new(),
        )
        .await;
        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();
        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::SubmitOrphanWrap,
            )
            .await
            .unwrap();
        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::ConfirmOrphanWrap,
            )
            .await
            .unwrap();
        ctx.store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::SubmitOrphanDeposit,
            )
            .await
            .unwrap();

        let seeded = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::OrphanDepositSubmitted {
            vault_deposit_tx_hash: seeded_deposit_tx,
            ..
        }) = seeded
        else {
            panic!("seeding should land in OrphanDepositSubmitted, got {seeded:?}");
        };

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
        };
        job.perform(&ctx)
            .await
            .expect("resume from OrphanDepositSubmitted should run to completion");

        let state = ctx.store.load(&recovery_id).await.unwrap();
        let Some(UnwrappedEquityRecovery::OrphanDeposited {
            vault_deposit_tx_hash,
            ..
        }) = state
        else {
            panic!("resume must complete the orphan path, got {state:?}");
        };
        assert_eq!(
            vault_deposit_tx_hash, seeded_deposit_tx,
            "the resumed run must confirm the persisted deposit tx, not submit a second deposit",
        );
    }

    /// Acceptance criterion (ADR 0017 SS4): a bot-gas receipt cost enqueue
    /// failure on `ConfirmOrphanWrap` must delayed-redrive the job rather
    /// than propagate terminally -- otherwise a bookkeeping write can consume
    /// the apalis retry budget and open this supervised worker's fail-stop
    /// circuit. `confirm_wrap` already succeeded on-chain and the aggregate
    /// has not advanced past `OrphanWrapSubmitted`, so redriving is safe: the
    /// resumed attempt dispatches straight to `resume_from_confirm_wrap`,
    /// never resending `SubmitOrphanWrap`.
    #[tokio::test]
    async fn confirm_orphan_wrap_bot_gas_enqueue_failure_redrives_without_terminal_error() {
        let symbol = Symbol::new("AAPL").unwrap();
        let equity_in_progress = HashMap::new();

        let (pool, apalis_pool) = crate::test_utils::setup_test_pools().await;
        let closed_apalis_pool = crate::test_utils::setup_test_apalis_pool().await;
        closed_apalis_pool.close().await;
        let bot_gas_queue =
            crate::bot_gas::RecordBotGasReceiptCostJobQueue::new(&closed_apalis_pool);

        let raindex: Arc<dyn Raindex> = Arc::new(MockRaindex::new());
        let wrapper: Arc<dyn Wrapper> = Arc::new(MockWrapper::new());
        let transfer_services = EquityTransferServices {
            raindex: raindex.clone(),
            vault_lookup: Arc::new(mock_vault_lookup()),
            tokenizer: Arc::new(MockTokenizer::new()),
            wrapper: wrapper.clone(),
            bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Disabled,
        };
        let mint_store = Arc::new(test_store(pool.clone(), transfer_services.clone()));
        let redemption_store = Arc::new(test_store(pool.clone(), transfer_services));
        let transfer = Arc::new(CrossVenueEquityTransfer::new(
            raindex.clone(),
            Arc::new(mock_vault_lookup()),
            Arc::new(MockTokenizer::new()),
            wrapper.clone(),
            Address::random(),
            mint_store.clone(),
            redemption_store.clone(),
        ));
        // The store's bot-gas enqueuer targets the CLOSED pool so
        // `ConfirmOrphanWrap`'s enqueue fails with a genuine `QueuePushError`.
        // `SubmitOrphanWrap` (used to seed state below) never calls the
        // enqueuer, so seeding is unaffected.
        let store = Arc::new(test_store(
            pool,
            UnwrappedEquityRecoveryServices {
                raindex,
                vault_lookup: Arc::new(mock_vault_lookup()),
                wrapper,
                transfer,
                wallet: Address::random(),
                bot_gas_enqueuer: BotGasReceiptCostEnqueuer::Enabled(bot_gas_queue),
            },
        ));
        let (sender, _receiver) = broadcast::channel(16);
        let view = view_with_unwrapped_balance(&symbol, FractionalShares::new(float!(5)));
        let inventory = Arc::new(BroadcastingInventory::new(view, sender));

        let ctx = UnwrappedEquityRecoveryCtx {
            inventory,
            store: store.clone(),
            mint_store,
            redemption_store,
            equity_in_progress: Arc::new(RwLock::new(equity_in_progress)),
            queue: UnwrappedEquityRecoveryJobQueue::new(&apalis_pool),
            reschedule_interval: Duration::from_secs(1),
        };
        let recovery_id = UnwrappedEquityRecoveryId(Uuid::new_v4());

        store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::Detect {
                    symbol: symbol.clone(),
                    shares: FractionalShares::new(float!(5)),
                },
            )
            .await
            .unwrap();
        store
            .send(
                &recovery_id,
                UnwrappedEquityRecoveryCommand::SubmitOrphanWrap,
            )
            .await
            .unwrap();
        let seeded = store.load(&recovery_id).await.unwrap();
        assert!(
            matches!(
                seeded,
                Some(UnwrappedEquityRecovery::OrphanWrapSubmitted { .. })
            ),
            "seeding should land in OrphanWrapSubmitted, got {seeded:?}",
        );

        let job = UnwrappedEquityRecoveryJob {
            symbol: symbol.clone(),
            recovery_id: recovery_id.clone(),
        };

        job.perform(&ctx)
            .await
            .expect("a bot-gas enqueue failure must not fail the recovery job terminally");

        let state = store.load(&recovery_id).await.unwrap();
        assert!(
            matches!(
                state,
                Some(UnwrappedEquityRecovery::OrphanWrapSubmitted { .. })
            ),
            "the aggregate must remain un-advanced (ConfirmOrphanWrap did not commit), \
             got {state:?}",
        );

        let (rescheduled,): (i64,) =
            sqlx_apalis::query_as("SELECT COUNT(*) FROM Jobs WHERE job_type = ?")
                .bind(std::any::type_name::<UnwrappedEquityRecoveryJob>())
                .fetch_one(&apalis_pool)
                .await
                .unwrap();
        assert_eq!(
            rescheduled, 1,
            "a bot-gas enqueue failure must re-enqueue a delayed replacement job",
        );
    }
}
