//! Server-to-client WebSocket statement envelope.
//!
//! [`Statement`] is the top-level tagged union pushed over WebSocket.
//! Each variant wraps a domain-specific payload. The [`guard_ts`](Statement::guard_ts)
//! method generates a TypeScript runtime type guard for message validation.

use serde::Serialize;
use strum::VariantNames;
use ts_rs::TS;

use crate::inventory::InventorySnapshot;
use crate::transfer::TransferOperation;
use crate::{CurrentState, Position, Trade};

/// Server-to-client WebSocket statements.
///
/// Each variant represents a domain-specific statement the server
/// pushes to connected clients. The `type` tag is serialized as
/// snake_case for the TypeScript client.
///
/// [`VariantNames`] derives `Statement::VARIANTS` — a compile-time
/// slice of all variant names in snake_case. Adding a variant
/// automatically updates the list; no manual bookkeeping needed.
/// The dashboard uses [`guard_ts`] output to validate incoming
/// WebSocket messages at runtime before dispatching.
#[derive(Debug, Clone, Serialize, VariantNames, TS)]
#[serde(tag = "type", content = "data", rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum Statement {
    CurrentState(Box<CurrentState>),
    TradeUpdate(Trade),
    PositionUpdate(Position),
    InventorySnapshot(Box<InventorySnapshot>),
    TransferUpdate(TransferOperation),
}

impl Statement {
    /// Generates a TypeScript module exporting `isStatement`, a runtime
    /// type guard for WebSocket message validation.
    ///
    /// `JSON.parse` returns `unknown`. The guard narrows it to
    /// `Statement` so the subsequent `matcher` call is type-safe —
    /// without it the dashboard would need an unsafe cast.
    ///
    /// Tags come from [`VARIANTS`] (derived by strum from this enum).
    /// The `satisfies StatementType[]` clause in the output gives a
    /// TypeScript-side compile error if the tags ever drift from the
    /// generated `Statement` type definition.
    ///
    /// The generated `isStatement` performs tag-only validation: it checks
    /// that the `type` field is a known `Statement` variant, but does not
    /// validate the shape of `data`. This is intentional — the TypeScript
    /// type system enforces payload shape after the type guard narrows to
    /// `Statement`, so per-variant structural checks would be redundant.
    /// Callers must not assume `data` is well-formed until they pattern-match
    /// on `type`.
    #[must_use]
    pub fn guard_ts() -> String {
        let tags = Self::VARIANTS
            .iter()
            .map(|tag| format!("  '{tag}'"))
            .collect::<Vec<_>>()
            .join(",\n");

        format!(
            r"// This file was generated by st0x-dto. Do not edit manually.
import type {{ Statement }} from './Statement'

type StatementType = Statement['type']

const STATEMENT_TYPES: Set<string> = new Set<StatementType>([
{tags}
] satisfies StatementType[])

export const isStatement = (value: unknown): value is Statement => {{
  if (typeof value !== 'object' || value === null) return false
  if (!('type' in value) || !('data' in value)) return false

  const record = value as Record<string, unknown>
  return typeof record['type'] === 'string' && STATEMENT_TYPES.has(record['type'])
}}
"
        )
    }
}

#[cfg(test)]
mod tests {
    use chrono::Utc;
    use serde_json::json;

    use st0x_finance::{FractionalShares, Symbol};
    use st0x_float_macro::float;

    use super::*;
    use crate::{Direction, Inventory, Settings, TradingVenue};

    #[test]
    fn statement_variants_matches_serde_wire_format() {
        assert_eq!(
            Statement::VARIANTS,
            &[
                "current_state",
                "trade_update",
                "position_update",
                "inventory_snapshot",
                "transfer_update"
            ]
        );
    }

    #[test]
    fn statement_guard_contains_all_variants() {
        let guard = Statement::guard_ts();
        for tag in Statement::VARIANTS {
            assert!(
                guard.contains(tag),
                "guard should contain tag '{tag}', got:\n{guard}"
            );
        }
        assert!(guard.contains("isStatement"));
        assert!(guard.contains("import type { Statement }"));
    }

    #[test]
    fn statement_trade_update_serializes_with_type_tag() {
        let trade = Trade {
            id: "0x0000000000000000000000000000000000000000000000000000000000000000:0".to_string(),
            occurred_at: Utc::now(),
            venue: TradingVenue::Raindex,
            direction: Direction::Buy,
            symbol: Symbol::new("AAPL").unwrap(),
            shares: FractionalShares::new(float!(10)),
            outcome: crate::TradeOutcome::Filled,
        };
        let msg = Statement::TradeUpdate(trade);
        let json = serde_json::to_value(&msg).expect("serialization should succeed");
        assert_eq!(json["type"], json!("trade_update"));
        assert_eq!(json["data"]["venue"], json!("raindex"));
        assert_eq!(json["data"]["direction"], json!("buy"));
        assert_eq!(json["data"]["symbol"], json!("AAPL"));
    }

    #[test]
    fn statement_current_state_serializes_with_type_tag() {
        let msg = Statement::CurrentState(Box::new(CurrentState {
            trades: Vec::new(),
            inventory: Inventory::empty(),
            positions: Vec::new(),
            settings: Settings {
                equity_target: 0.5,
                equity_deviation: 0.2,
                usdc_target: None,
                usdc_deviation: None,
                cash_reserved: None,
                execution_threshold: "1 share".to_string(),
                assets: Vec::new(),
                wallet: None,
                log_level: "Debug".to_string(),
                server_port: 8001,
                orderbook: "0x0".to_string(),
                deployment_block: 0,
                trading_mode: "standalone".to_string(),
                broker: "dry_run".to_string(),
                order_polling_interval: 5,
                inventory_poll_interval: 15,
            },
            active_transfers: Vec::new(),
            recent_transfers: Vec::new(),
            warnings: Vec::new(),
        }));
        let json = serde_json::to_value(&msg).expect("serialization should succeed");
        assert_eq!(json["type"], json!("current_state"));
        assert_eq!(json["data"]["trades"], json!([]));
        assert_eq!(json["data"]["positions"], json!([]));
    }

    #[test]
    fn statement_position_update_serializes_with_type_tag() {
        let msg = Statement::PositionUpdate(Position {
            symbol: Symbol::new("AAPL").unwrap(),
            net: rain_math_float::Float::parse("5.5".to_string()).unwrap(),
            last_price_usdc: None,
        });
        let json = serde_json::to_value(&msg).expect("serialization should succeed");
        assert_eq!(json["type"], json!("position_update"));
        assert_eq!(json["data"]["symbol"], json!("AAPL"));
        assert_eq!(json["data"]["net"], json!("5.5"));
    }

    #[test]
    fn statement_inventory_snapshot_serializes_with_type_tag() {
        let msg = Statement::InventorySnapshot(Box::new(InventorySnapshot {
            inventory: Inventory::empty(),
            fetched_at: Utc::now(),
        }));
        let json = serde_json::to_value(&msg).expect("serialization should succeed");
        assert_eq!(json["type"], json!("inventory_snapshot"));
    }
}
